<?php

$link= mysqli_connect('localhost', 'root','root') or
die('Can not connect to server!');
mysqli_select_db($link,'store')  or
die('Can not connect to database!');
?>
<?php

$title = 'Каталог';
$color = 'black';

include('header.php');
//include('Connect.php');

//$strSQL2='SELECT * FROM categories ORDER BY name_cat';
//print ($strSQL2);
$result2=mysqli_query($link, 'SELECT * FROM categories ORDER BY name_cat')
   or die('Не могу выполнить запрос!');

echo <<<HERE
<tr><td>
        <table border=0 align = "right" width = "70%" cellpadding = "0" cellspacing = "0">
            <tr><td><center><br> <h2  style="color: white">Категории</h2> </center><ul style="color: white">
HERE;
                        while($row=mysqli_fetch_array($result2))
                        {
                        echo '<center><li><a style="color: white" href ="show.phtml?&id_cat=
                            '.$row['id_cat'].'">'.$row['name_cat'].'</a></li></center>'; }
echo <<<HERE
                    </ul></td>
                 </tr>
</table>

</td></tr><br>
HERE;


include('footer.php');
mysqli_close();
?>
