<?php

$link= mysqli_connect('localhost', 'root','root') or
die('Can not connect to server!');
mysqli_select_db($link,'store')  or
die('Can not connect to database!');
?>
<?php
$id_cat=$HTTP_GET_VARS['id_cat'];


//$strSQL1="SELECT name_cat FROM  categories WHERE id_cat=.$id_cat";

$result=mysqli_query($link, 'SELECT name_cat FROM  categories WHERE id_cat='.$id_cat)
or die("Не могу выполнить запрос1!");

if($row=mysqli_fetch_array($result))
    $title=$row["name_cat"];
    $strSQL1= mysqli_query($link, "SELECT  name_pr, price_pr, proizvod_pr, sostav_pr, srok_pr, name_cat 
FROM products, categories 
WHERE store.id_cat=categories.id_cat 
  AND store.id_cat=".$id_cat);

$result1=mysqli_query($link,$strSQL1)
or die("Не могу выполнить запрос2!");

include('header.php');
echo <<<HERE

    <tr><td> <table border="1" width="100%" align="right" >
    <?
                 while($row=mysql_fetch_array($result1)) 
                  {?>
                    <tr><td align="center"><img src="images/<?print $row['image'];?>
"alt="<?print $row['name_pr'];?>" border="0">
                       <center><a href="dobasket.phtml?id_pr= <?print $row['id_pr'];?>">
                               <font size=-1>положить в корзину</font></a></center></td>
                        <td>   <table>
                                <tr><td align="right"><i>Название: </i></td>    <td>print $row['name_pr'];</td></tr>
                                <tr><td align="right"><i>Цена: </i></td>    <td>print $row['price_pr'];</td></tr>
                                <tr><td align="right"><i>Производитель: </i></td>    <td>print $row['proizvod_pr'];</td></tr>
                                <tr><td align="right"><i>Состав: </i></td>    <td>print $row['sostav_pr'];</td></tr>
                                <tr><td align="right"><i>Срок годности: </i></td>    <td>print $row['srok_pr'];</td></tr>
                                <tr><td align="right"><i>Категория: </i></td>    <td><a href="show.phtml?id_cat= <?print $row["id_cat"];?>">print $row["name_cat"];</a>    </td></tr>
                            </table>
                        </td>
                    </tr>  </table> </td></tr>``
HERE;
 include('footer.php');
?>